[build]
  command = "pnpm exec nx build website"
  publish = "apps/website/dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"

[context.deploy-preview.environment]
  COMING_SOON = "false"

[context.branch-deploy.environment]
  COMING_SOON = "false"
